package playlist

type Playlist struct {
	Owner                   User
	Cover                   Cover
	Made_for                Made_for
	Play_counter            Play_counter
	Playlist_absence        Playlist_absence
	Uid                     int
	Kind                    int
	Title                   string
	Track_count             int
	Tags                    []interface{}
	Revision                int
	Snapshot                int
	Visibility              string
	Collective              bool
	Url_part                string
	Created                 string
	Modified                string
	Available               bool
	Is_banner               bool
	Is_premiere             bool
	Duration_ms             int
	Og_image                string
	Og_title                string
	Og_description          string
	Image                   string
	Cover_without_text      Cover
	Contest                 Contest
	Background_color        string
	Text_color              string
	Id_for_from             string
	Dummy_description       string
	Dummy_page_description  string
	Dummy_cover             Cover
	Dummy_rollover_cover    Cover
	Og_data                 Open_graph_data
	Branding                Brand
	Metrika_id              int
	Coauthors               []int
	Top_artist              []Artist
	Recent_tracks           []Track_id
	Tracks                  []Track_short
	Prerolls                []interface{}
	Likes_count             int
	Similar_playlists       []Playlist
	Last_owner_playlists    []Playlist
	Generated_playlist_type string
	Animated_cover_uri      string
	Ever_played             bool
	Description             string
	Description_formatted   string
	Playlist_uuid           string
	Type                    string
	Ready                   bool
	Is_for_from             interface{}
	Regions                 interface{}
	Custom_wave             Custom_wave
	Pager                   Pager
}
