package entities

type Album struct {
	Id                       int            `json:"id,omitempty"`
	Error                    string         `json:"error,omitempty"`
	Title                    string         `json:"title,omitempty"`
	TrackCount               int            `json:"trackCount,omitempty"`
	Artists                  []Artist       `json:"artists,omitempty"`
	Labels                   []string       `json:"labels,omitempty"`
	Available                bool           `json:"available,omitempty"`
	AvailableForPremiumUsers bool           `json:"availableForPremiumUsers,omitempty"`
	Version                  string         `json:"version,omitempty"`
	CoverUri                 string         `json:"coverUri,omitempty"`
	ContentWarning           string         `json:"contentWarning,omitempty"`
	OriginalReleaseYear      interface{}    `json:"originalRelease_Year,omitempty"`
	Genre                    string         `json:"genre,omitempty"`
	TextColor                string         `json:"textColor,omitempty"`
	ShortDescription         string         `json:"shortDescription,omitempty"`
	Description              string         `json:"description,omitempty"`
	IsPremiere               bool           `json:"isPremiere,omitempty"`
	IsBanner                 bool           `json:"isBanner,omitempty"`
	MetaType                 string         `json:"metaType,omitempty"`
	StorageDir               string         `json:"storageDir,omitempty"`
	OgImage                  string         `json:"ogImage,omitempty"`
	Buy                      []interface{}  `json:"buy,omitempty"`
	Recent                   bool           `json:"recent,omitempty"`
	VeryImportant            bool           `json:"veryImportant,omitempty"`
	AvailableForMobile       bool           `json:"availableForMobile,omitempty"`
	AvailablePartially       bool           `json:"availablePartially,omitempty"`
	Bests                    []int          `json:"bests,omitempty"`
	Duplicates               []Album        `json:"duplicates,omitempty"`
	Prerolls                 []interface{}  `json:"prerolls,omitempty"`
	Volumes                  [][]Track      `json:"volumes,omitempty"`
	Year                     int            `json:"year,omitempty"`
	ReleaseDate              string         `json:"releaseDate,omitempty"`
	Type          string        `json:"type,omitempty"`
	TrackPosition TrackPosition `json:"trackPosition"`
	Regions       []string      `json:"regions,omitempty"`
	AvailableAsRbt           bool           `json:"availableAsRbt,omitempty"`
	LyricsAvailable          bool           `json:"lyricsAvailable,omitempty"`
	RememberPosition         bool           `json:"rememberPosition,omitempty"`
	Albums                   []Album        `json:"albums,omitempty"`
	DurationMs               int            `json:"durationMs,omitempty"`
	Explicit                 bool           `json:"explicit,omitempty"`
	StartDate                string         `json:"startDate,omitempty"`
	LikesCount               int            `json:"likesCount,omitempty"`
	Deprecation              Deprecation    `json:"deprecation"`
	AvailableRegions         []string       `json:"availableRegions,omitempty"`
	AvailableForOptions      []string       `json:"availableForOptions,omitempty"`
}
